In [1]:
import tensorflow as tf
import numpy as np
import math
import sys

In [2]:
model = tf.keras.models.load_model(r'C:\Users\srico\Documents\BEARHW\Image Classification CNN\models\model.h5')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 6, 6, 8)           80        
                                                                 
 max_pooling2d (MaxPooling2D  (None, 3, 3, 8)          0         
 )                                                               
                                                                 
 flatten (Flatten)           (None, 72)                0         
                                                                 
 dense (Dense)               (None, 10)                730       
                                                                 
Total params: 810
Trainable params: 810
Non-trainable params: 0
_________________________________________________________________


In [3]:
# Create a new model that will return outputs of all intermediate layers
layer_outputs = [layer.output for layer in model.layers]  # List of intermediate layer outputs
intermediate_model = tf.keras.Model(inputs=model.input, outputs=layer_outputs)

In [4]:
import numpy as np

# Example input data, assuming the input shape is (1, 8, 8, 1)
input_data = np.array([
    0.0, 0.0, 0.3125, 0.8125, 0.5625, 0.0625, 0.0, 0.0, 0.0, 0.0, 
    0.8125, 0.9375, 0.625, 0.9375, 0.3125, 0.0, 0.0, 0.1875, 0.9375, 0.125, 
    0.0, 0.6875, 0.5, 0.0, 0.0, 0.25, 0.75, 0.0, 0.0, 0.5, 
    0.5, 0.0, 0.0, 0.3125, 0.5, 0.0, 0.0, 0.5625, 0.5, 0.0, 
    0.0, 0.25, 0.6875, 0.0, 0.0625, 0.75, 0.4375, 0.0, 0.0, 0.125, 
    0.875, 0.3125, 0.625, 0.75, 0.0, 0.0, 0.0, 0.0, 0.375, 0.8125, 
    0.625, 0.0, 0.0, 0.0,
]).reshape(1, 8, 8, 1).astype(np.float32)

# Get the intermediate layer outputs
intermediate_outputs = intermediate_model(input_data)


In [5]:
# Print the outputs of each layer
for layer, output in zip(model.layers, intermediate_outputs):
    print(f"Output of layer {layer.name}: {output.numpy()}")

Output of layer conv2d: [[[[0.95353466 0.         1.2029399  0.         1.8446589  1.1326841
    0.         0.        ]
   [2.8136399  0.         2.3423574  0.16445473 2.1892896  1.1388681
    0.3176513  0.        ]
   [2.8030372  0.32161674 3.0093622  1.7498195  0.7465464  0.
    2.235262   0.24579245]
   [2.2858536  0.         2.6526148  1.4764743  1.0869063  0.
    1.8631382  0.5413518 ]
   [2.562481   0.         1.3750668  0.08665054 1.4874164  0.31211796
    0.9906652  0.        ]
   [1.424877   0.2536646  0.51710474 0.         1.0113033  0.
    1.3396316  0.        ]]

  [[1.2898009  0.15609658 1.7212894  0.11982755 2.0384324  1.4549541
    0.         0.09343165]
   [2.94999    0.42540526 2.2453415  1.3307467  1.0062621  0.26704496
    1.212928   0.        ]
   [1.6978055  1.6796619  1.8259594  2.529538   0.14350866 0.
    2.6904998  1.3513912 ]
   [1.3461654  1.1247172  2.0690184  2.015191   1.0559984  0.28435263
    1.1525468  1.7042546 ]
   [2.7027938  0.         2.3156664  1.

In [6]:
intermediate_model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_input (InputLayer)   [(None, 8, 8, 1)]         0         
                                                                 
 conv2d (Conv2D)             (None, 6, 6, 8)           80        
                                                                 
 max_pooling2d (MaxPooling2D  (None, 3, 3, 8)          0         
 )                                                               
                                                                 
 flatten (Flatten)           (None, 72)                0         
                                                                 
 dense (Dense)               (None, 10)                730       
                                                                 
Total params: 810
Trainable params: 810
Non-trainable params: 0
_______________________________________________________________

In [15]:
# Extract the output of the convolutional layer
conv_layer_output = model.get_layer('conv2d').output

# Create a new model that takes the same input but outputs only the convolutional layer's output
conv_model = tf.keras.Model(inputs=model.input, outputs=conv_layer_output)

# Print the summary of the new convolutional layer model
conv_model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_input (InputLayer)   [(None, 8, 8, 1)]         0         
                                                                 
 conv2d (Conv2D)             (None, 6, 6, 8)           80        
                                                                 
Total params: 80
Trainable params: 80
Non-trainable params: 0
_________________________________________________________________


In [16]:
# Example input data, assuming the input shape is (1, 8, 8, 1)
input_data = np.array([
    0.0, 0.0, 0.3125, 0.8125, 0.5625, 0.0625, 0.0, 0.0, 0.0, 0.0, 
    0.8125, 0.9375, 0.625, 0.9375, 0.3125, 0.0, 0.0, 0.1875, 0.9375, 0.125, 
    0.0, 0.6875, 0.5, 0.0, 0.0, 0.25, 0.75, 0.0, 0.0, 0.5, 
    0.5, 0.0, 0.0, 0.3125, 0.5, 0.0, 0.0, 0.5625, 0.5, 0.0, 
    0.0, 0.25, 0.6875, 0.0, 0.0625, 0.75, 0.4375, 0.0, 0.0, 0.125, 
    0.875, 0.3125, 0.625, 0.75, 0.0, 0.0, 0.0, 0.0, 0.375, 0.8125, 
    0.625, 0.0, 0.0, 0.0,
]).reshape(1, 8, 8, 1).astype(np.float32)

# Get the intermediate layer outputs
conv_output = conv_model(input_data)
print(f"Output of the convolutional layer: {conv_output.numpy()}")

Output of the convolutional layer: [[[[0.95353466 0.         1.2029399  0.         1.8446589  1.1326841
    0.         0.        ]
   [2.8136399  0.         2.3423574  0.16445473 2.1892896  1.1388681
    0.3176513  0.        ]
   [2.8030372  0.32161674 3.0093622  1.7498195  0.7465464  0.
    2.235262   0.24579245]
   [2.2858536  0.         2.6526148  1.4764743  1.0869063  0.
    1.8631382  0.5413518 ]
   [2.562481   0.         1.3750668  0.08665054 1.4874164  0.31211796
    0.9906652  0.        ]
   [1.424877   0.2536646  0.51710474 0.         1.0113033  0.
    1.3396316  0.        ]]

  [[1.2898009  0.15609658 1.7212894  0.11982755 2.0384324  1.4549541
    0.         0.09343165]
   [2.94999    0.42540526 2.2453415  1.3307467  1.0062621  0.26704496
    1.212928   0.        ]
   [1.6978055  1.6796619  1.8259594  2.529538   0.14350866 0.
    2.6904998  1.3513912 ]
   [1.3461654  1.1247172  2.0690184  2.015191   1.0559984  0.28435263
    1.1525468  1.7042546 ]
   [2.7027938  0.         2.

In [7]:
from sklearn.datasets import load_digits
def get_data():
    np.random.seed(1337)
    x_values, y_values = load_digits(return_X_y=True)
    x_values /= x_values.max()
    # reshape to (8 x 8 x 1)
    x_values = x_values.reshape((len(x_values), 8, 8, 1))
    # split into train, validation, test
    TRAIN_SPLIT = int(0.6 * len(x_values))
    TEST_SPLIT = int(0.2 * len(x_values) + TRAIN_SPLIT)
    x_train, x_test, x_validate = np.split(x_values, [TRAIN_SPLIT, TEST_SPLIT])
    y_train, y_test, y_validate = np.split(y_values, [TRAIN_SPLIT, TEST_SPLIT])
    return x_train, x_test, x_validate, y_train, y_test, y_validate


# Define a representative dataset generator for quantization
def representative_dataset():
    X_train, X_test, X_validate, y_train, y_test, y_validate = get_data()
    for i in range(len(X_train)):
        input_data = np.array([X_train[i]], dtype=np.float32)
        yield [input_data]

In [8]:
# Convert the model to TensorFlow Lite format with quantization
converter = tf.lite.TFLiteConverter.from_keras_model(intermediate_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # Quantize input
converter.inference_output_type = tf.int8  # Quantize output
tflite_quant_model = converter.convert()

INFO:tensorflow:Assets written to: C:\Users\srico\AppData\Local\Temp\tmpl6h1y5wa\assets


INFO:tensorflow:Assets written to: C:\Users\srico\AppData\Local\Temp\tmpl6h1y5wa\assets
c:\Users\srico\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\lite\python\convert.py:765: UserWarning: Statistics for quantized inputs were expected, but not specified; continuing anyway.
  warnings.warn("Statistics for quantized inputs were expected, but not "


In [9]:
# Save the quantized model
with open('inter_model.tflite', 'wb') as f:
    f.write(tflite_quant_model)

In [19]:
# Load the TFLite model and allocate tensors
interpreter = tf.lite.Interpreter(model_path=r"C:\Users\srico\Documents\BEARHW\Image Classification CNN\python_scripts\inter_model.tflite")
interpreter.allocate_tensors()

# Get input and output tensors
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Print input details
print("Input Details:")
for detail in input_details:
    print(detail)

# Print output details
print("Output Details:")
for detail in output_details:
    print(detail)

# Print model layers and their details
def print_tensor_details(interpreter):
    tensor_details = interpreter.get_tensor_details()
    for tensor in tensor_details:
        print(f"Name: {tensor['name']}, Index: {tensor['index']}, Shape: {tensor['shape']}, Type: {tensor['dtype']}, Quantization Parameters: {tensor['quantization_parameters']}")

print_tensor_details(interpreter)


Input Details:
{'name': 'serving_default_conv2d_input:0', 'index': 0, 'shape': array([1, 8, 8, 1]), 'shape_signature': array([-1,  8,  8,  1]), 'dtype': <class 'numpy.int8'>, 'quantization': (0.003921568859368563, -128), 'quantization_parameters': {'scales': array([0.00392157], dtype=float32), 'zero_points': array([-128]), 'quantized_dimension': 0}, 'sparsity_parameters': {}}
Output Details:
{'name': 'StatefulPartitionedCall:0', 'index': 6, 'shape': array([1, 6, 6, 8]), 'shape_signature': array([-1,  6,  6,  8]), 'dtype': <class 'numpy.int8'>, 'quantization': (0.019547035917639732, -128), 'quantization_parameters': {'scales': array([0.01954704], dtype=float32), 'zero_points': array([-128]), 'quantized_dimension': 0}, 'sparsity_parameters': {}}
{'name': 'StatefulPartitionedCall:3', 'index': 7, 'shape': array([1, 3, 3, 8]), 'shape_signature': array([-1,  3,  3,  8]), 'dtype': <class 'numpy.int8'>, 'quantization': (0.019547035917639732, -128), 'quantization_parameters': {'scales': array([

Testing TFLITE

In [3]:
import tensorflow as tf
import numpy as np

# Load the TFLite model and allocate tensors
interpreter = tf.lite.Interpreter(model_path=r"C:\Users\srico\Documents\BEARHW\Image Classification CNN\python_scripts\inter_model.tflite")
interpreter.allocate_tensors()

# Get input and output tensors
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

input_scale, input_zero_point = input_details[0]['quantization']
print(f"Input scale: {input_scale}, Input zero point: {input_zero_point}")

# Quantize the float input data
input_data = np.array([
    0.0, 0.0, 0.3125, 0.8125, 0.5625, 0.0625, 0.0, 0.0, 0.0, 0.0, 
    0.8125, 0.9375, 0.625, 0.9375, 0.3125, 0.0, 0.0, 0.1875, 0.9375, 0.125, 
    0.0, 0.6875, 0.5, 0.0, 0.0, 0.25, 0.75, 0.0, 0.0, 0.5, 
    0.5, 0.0, 0.0, 0.3125, 0.5, 0.0, 0.0, 0.5625, 0.5, 0.0, 
    0.0, 0.25, 0.6875, 0.0, 0.0625, 0.75, 0.4375, 0.0, 0.0, 0.125, 
    0.875, 0.3125, 0.625, 0.75, 0.0, 0.0, 0.0, 0.0, 0.375, 0.8125, 
    0.625, 0.0, 0.0, 0.0
]).reshape(1, 8, 8, 1).astype(np.float32)  # Replace with actual input data
quantized_input_data = np.round(input_data / input_scale) + input_zero_point
quantized_input_data = quantized_input_data.astype(np.int8)

print("Quantized Input Data:")
print(np.array(quantized_input_data).flatten())

# Set the input tensor
interpreter.set_tensor(input_details[0]['index'], quantized_input_data)

# Run the model (invoke the interpreter)
interpreter.invoke()

# Get the output tensor
output_data = interpreter.get_tensor(output_details[0]['index'])

# Print the quantized output data
print("Quantized Output Data:")
output_data = np.array(output_data).flatten()
print(output_data)

# Extract output quantization parameters
output_scale, output_zero_point = output_details[0]['quantization']
print(f"Output scale: {output_scale}, Output zero point: {output_zero_point}")

# Dequantize the output data
dequantized_output_data = (output_data - output_zero_point) * output_scale

# Print the dequantized output data
print("Dequantized Output Data:")
print(dequantized_output_data)

# Print biases and filter data
tensor_details = interpreter.get_tensor_details()

# for tensor in tensor_details:
#     if 'bias' in tensor['name'] or 'BiasAdd' in tensor['name']:
#         print(f"Biases for {tensor['name']}:")
#         tensor_index = tensor['index']
#         bias_data = interpreter.tensor(tensor_index)()
#         print(bias_data.flatten())
#     if 'conv' in tensor['name'] or 'Conv2D' in tensor['name'] or 'filter' in tensor['name']:
#         print(f"Filters for {tensor['name']}:")
#         tensor_index = tensor['index']
#         filter_data = interpreter.tensor(tensor_index)()
#         print(filter_data.flatten())


Input scale: 0.003921568859368563, Input zero point: -128
Quantized Input Data:
[-128 -128  -48   79   15 -112 -128 -128 -128 -128   79  111   31  111
  -48 -128 -128  -80  111  -96 -128   47   -1 -128 -128  -64   63 -128
 -128   -1   -1 -128 -128  -48   -1 -128 -128   15   -1 -128 -128  -64
   47 -128 -112   63  -16 -128 -128  -96   95  -48   31   63 -128 -128
 -128 -128  -32   79   31 -128 -128 -128]
Quantized Output Data:
[ -79 -128  -66 -128  -33  -70 -128 -128   16 -128   -8 -119  -16  -70
 -112 -128   16 -111   26  -39  -90 -128  -14 -116  -11 -128    8  -52
  -72 -128  -33 -100    3 -128  -58 -123  -52 -112  -77 -128  -55 -115
 -102 -128  -76 -128  -59 -128  -62 -120  -40 -122  -24  -54 -128 -123
   23 -106  -13  -60  -76 -115  -66 -128  -41  -42  -35    1 -120 -128
   10  -59  -59  -71  -22  -25  -74 -113  -69  -40   10 -128  -10  -71
  -77 -128  -67 -122  -28 -116  -80  -86  -91 -128  -41 -112  -55 -105
  -38  -97  -41  -65 -119 -109   -4 -121  -40  -73 -116 -128  -54 -128
  -

In [30]:
import tensorflow as tf
import numpy as np

# Function to calculate multiplier and shift
def calculate_multiplier_shift(effective_scale):
    significand, exponent = np.frexp(effective_scale)
    significand_q31 = np.round(significand * (1 << 31)).astype(np.int64)
    return significand_q31, exponent

# Load the TFLite model and allocate tensors
interpreter = tf.lite.Interpreter(model_path=r"C:\Users\srico\Documents\BEARHW\Image Classification CNN\python_scripts\conv_model.tflite")
interpreter.allocate_tensors()

# Get input and output tensors
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Extract input quantization parameters
input_scale, input_zero_point = input_details[0]['quantization']
print(f"Input scale: {input_scale}, Input zero point: {input_zero_point}")

# Extract output quantization parameters
output_scale, output_zero_point = output_details[0]['quantization']
print(f"Output scale: {output_scale}, Output zero point: {output_zero_point}")

# Function to check if a layer is a convolutional layer
def is_convolutional_layer(tensor_name):
    return ('conv' in tensor_name.lower() or 'conv2d' in tensor_name.lower()) and 'input' not in tensor_name.lower()

# Print biases and filter data, and calculate multipliers and shifts
tensor_details = interpreter.get_tensor_details()

conv_weight_tensors = [tensor for tensor in tensor_details if is_convolutional_layer(tensor['name'])]
if conv_weight_tensors:
    for weight_tensor in conv_weight_tensors:
        weight_scales = weight_tensor['quantization_parameters']['scales']
        effective_scales = input_scale * weight_scales / output_scale

        # Calculate the multiplier and shift for each channel
        multipliers, shifts = calculate_multiplier_shift(effective_scales)

        print(f"Effective Scales for {weight_tensor['name']}: {effective_scales}")
        print(f"Multipliers for {weight_tensor['name']}: {multipliers}")
        print(f"Shifts for {weight_tensor['name']}: {shifts}")
else:
    print("No convolutional layer found.")


Input scale: 0.003921568859368563, Input zero point: -128
Output scale: 0.019547035917639732, Output zero point: -128
Effective Scales for model_1/conv2d/BiasAdd/ReadVariableOp: [7.4180207e-06 6.9111993e-06 6.7407577e-06 7.0267238e-06 8.0817417e-06
 6.7285159e-06 6.3836942e-06 7.1689055e-06]
Multipliers for model_1/conv2d/BiasAdd/ReadVariableOp: [2087987200 1945329664 1897354624 1977846912 1137404032 1893908864
 1796850176 2017867520]
Shifts for model_1/conv2d/BiasAdd/ReadVariableOp: [-17 -17 -17 -17 -16 -17 -17 -17]
Effective Scales for model_1/conv2d/Conv2D: [0.0018916  0.00176236 0.00171889 0.00179181 0.00206084 0.00171577
 0.00162784 0.00182807]
Multipliers for model_1/conv2d/Conv2D: [2079830784 1937730560 1889943040 1970120960 1132961024 1886510720
 1789831296 2009985152]
Shifts for model_1/conv2d/Conv2D: [-9 -9 -9 -9 -8 -9 -9 -9]


In [5]:

# Load the TFLite model and allocate tensors
interpreter = tf.lite.Interpreter(model_path=r"C:\Users\srico\Documents\BEARHW\Image Classification CNN\models\quantized_CNN_model.tflite")
interpreter.allocate_tensors()

# Get input and output tensor details
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Function to get all layer outputs
# Function to get all layer outputs
def get_all_intermediate_outputs(interpreter, input_data):
    # Set the input tensor
    interpreter.set_tensor(input_details[0]['index'], input_data)
    
    # Run the interpreter
    interpreter.invoke()
    
    # Get outputs for all layers
    all_outputs = {}
    tensor_details = interpreter.get_tensor_details()
    
    for details in tensor_details:
        try:
            output_data = interpreter.get_tensor(details['index'])
            all_outputs[details['name']] = output_data
        except ValueError:
            # Skip tensors that cannot be retrieved
            continue
        
    return all_outputs
# Prepare the input data as per your model's requirements
input_data = np.array([
    0.0, 0.0, 0.4375, 0.5, 0.8125, 1.0, 0.9375, 0.0625, 0.0, 0.0, 
    0.4375, 0.4375, 0.25, 0.6875, 0.75, 0.0, 0.0, 0.0, 0.0, 0.0, 
    0.5, 0.8125, 0.0625, 0.0, 0.0, 0.25, 0.5, 0.5, 0.9375, 0.9375, 
    0.375, 0.0, 0.0, 0.125, 0.6875, 0.9375, 0.9375, 0.25, 0.0, 0.0, 
    0.0, 0.0, 0.0, 1.0, 0.3125, 0.0, 0.0, 0.0, 0.0, 0.0, 
    0.5625, 0.9375, 0.0625, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8125, 0.3125, 
    0.0, 0.0, 0.0, 0.0
]).reshape(1, 8, 8, 1).astype(np.float32)  # Replace with actual input data

input_scale, input_zero_point = input_details[0]['quantization']
print(f"Input scale: {input_scale}, Input zero point: {input_zero_point}")

# Extract output quantization parameters
output_scale, output_zero_point = output_details[0]['quantization']
print(f"Output scale: {output_scale}, Output zero point: {output_zero_point}")

quantized_input_data = np.round(input_data / input_scale) + input_zero_point
quantized_input_data = quantized_input_data.astype(np.int8)

print("Quantized Input Data:")
print(np.array(quantized_input_data).flatten())

# Get all intermediate layer outputs
intermediate_outputs = get_all_intermediate_outputs(interpreter, quantized_input_data)

# Print all intermediate layer outputs
for layer_name, output_data in intermediate_outputs.items():
    print(f"Layer: {layer_name}")
    print(output_data)


Input scale: 0.003921568859368563, Input zero point: -128
Output scale: 0.11720886081457138, Output zero point: 60
Quantized Input Data:
[-128 -128  -16   -1   79  127  111 -112 -128 -128  -16  -16  -64   47
   63 -128 -128 -128 -128 -128   -1   79 -112 -128 -128  -64   -1   -1
  111  111  -32 -128 -128  -96   47  111  111  -64 -128 -128 -128 -128
 -128  127  -48 -128 -128 -128 -128 -128   15  111 -112 -128 -128 -128
 -128 -128   79  -48 -128 -128 -128 -128]
Layer: serving_default_conv2d_input:0
[[[[-128]
   [-128]
   [ -16]
   [  -1]
   [  79]
   [ 127]
   [ 111]
   [-112]]

  [[-128]
   [-128]
   [ -16]
   [ -16]
   [ -64]
   [  47]
   [  63]
   [-128]]

  [[-128]
   [-128]
   [-128]
   [-128]
   [  -1]
   [  79]
   [-112]
   [-128]]

  [[-128]
   [ -64]
   [  -1]
   [  -1]
   [ 111]
   [ 111]
   [ -32]
   [-128]]

  [[-128]
   [ -96]
   [  47]
   [ 111]
   [ 111]
   [ -64]
   [-128]
   [-128]]

  [[-128]
   [-128]
   [-128]
   [ 127]
   [ -48]
   [-128]
   [-128]
   [-128]]

  [[-12